spring:
    jpa:
        show-sql: true
    datasource:
        url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
        username: sa
        password: sa
    h2:
        console:
            enabled: true
data:
    load:
        user-input: input/users.txt
        transaction-input: input/transactions.txt
        enabled: true
management:
    endpoints:
        web:
            exposure:
                include: "*"